# plugins/config.yaml - Main plugin configuration file
plugins:
  # Nemo Check Example
  - name: "NemoCheck"
    kind: "plugins.examples.nemocheck.plugin.NemoCheck"
    description: "Adapter for nemo check server"
    version: "0.1.0"
    author: "Julian Stephen"
    hooks: ["tool_pre_invoke", "tool_post_invoke"]
    tags: ["plugin", "pre-post"]
    mode: "enforce"  # enforce | permissive | disabled
    priority: 150
    config:
      nemo_guardrails_url: "http://nemo-guardrails-service:8000"
      # Replace with model name guardrailed by NeMo, for logging
      nemo_model: "model-org/guardrailed-model"

# Plugin directories to scan
plugin_dirs:
  - "plugins/native"                # Built-in plugins
  - "plugins/custom"                # Custom organization plugins
  - "/etc/mcpgateway/plugins"       # System-wide plugins
  - "plugins/examples/nemo"         # Example Nemo guardrails plugins
  - "plugins/examples/nemocheck"    # Nemo Check Server plugins

# Global plugin settings
plugin_settings:
  parallel_execution_within_band: true
  plugin_timeout: 30
  fail_on_plugin_error: false
  enable_plugin_api: true
  plugin_health_check_interval: 60
